### ISSUE TITLE
Byte order mark characters

### ISSUE THREAD

**Issue by djmccormick** [schorfES/node-lintspaces#12]
Byte order mark character (BOM) at the beginning of a file causes lintspaces to report unexpected spaces. It would be good if this was a configurable option.

**Comment by schorfES** [comment]
Hi, yes this is also a plan for the future as you can also see in this PR https://github.com/schorfES/node-lintspaces/pull/10. Hope we get this to work as soon as possible.

**Comment by schorfES** [comment]
The PR #10 is now released.
