### ISSUE TITLE
Latest version will not install on Mac OS X Mavericks

### ISSUE THREAD

**Issue by alduethadyn** [schorfES/node-lintspaces#14]
It looks like the pinned version of editorconfig being requested by node-lintspaces has some non Mac compatible pathing. The latest version of editor config does indeed install. Let me know if you need more information...

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/a936040/.nvm/v0.10.38/bin/npm" "install" "lintspaces@latest"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.6
npm ERR! path /Users/a936040/Workspace/coreui/node/node-browse/node_modules/lintspaces/node_modules/editorconfig/bin\editorconfig
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod '/Users/a936040/Workspace/coreui/node/node-browse/node_modules/lintspaces/node_modules/editorconfig/bin\editorconfig'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a936040/Workspace/coreui/node/node-browse/npm-debug.log

**Comment by schorfES** [comment]
Yes, this is an issue according to the editorconfig dependency in order to your npm version. I'll try to figure out this problem (maybe simply update the dependency to editorconfig). To get around this issue you can downgrade your npm for the installation – grrrrrrrrrrrrrr :-1:

**Comment by schorfES** [comment]
See also issue #16
