### ISSUE TITLE
Supporting editorconfig version 1.0.1

### ISSUE THREAD

**Issue by dantevvp** [schorfES/node-lintspaces#192]
Hey! We're using `node-lintspaces` in one of our plugins at Code Climate to analyze code using `editorconfig`. We're looking to update the plugin with `editorconfig` `1.0.1`. I noticed that the package is already updated in `master` to that version, but it's not yet released. Is there an ETA for a release supporting said version?

Thanks!

**Comment by schorfES** [comment]
Hi @dantevvp, thanks for using `node-lintspaces` ❤️ and pointing to this issue. I've created [a release `0.10.1`](https://github.com/schorfES/node-lintspaces/releases/tag/0.10.1) including the latest dependency updates.

**Comment by dantevvp** [comment]
Thank you!
