### ISSUE TITLE
indent tags, not attributes, for html files

### ISSUE THREAD

**Issue by mlarcher** [schorfES/node-lintspaces#23]
When dealing with html files, it's often useful to align the attributes of a given tag together. As the tag name vary in length, this implies that the lines beginning with an attribute will not comply with the indentation setting. This is usually handled by editorconfig based plugins, but is treated as an error by gulp-lintspaces.

**Comment by schorfES** [comment]
Have you tried to specify your own regular expression to ignore lines?

**Comment by mlarcher** [comment]
Let me answer your question with another question, if I may: is it possible to specify an "ignore" regular expression that would only apply to a particular type of file ? (i.e. html files only for instance)

**Comment by schorfES** [comment]
The node lintspaces validator only runs agains a single file when calling ```validate()```. So you may change your settings depending on filetype or create a new instance of the validator.
