### ISSUE TITLE
Check for newline character

### ISSUE THREAD

**Issue by HenningCash** [schorfES/node-lintspaces#25]
I would love to see a check for newline characters that can be either set to e.g.
- `IGNORE` (all types allowed - default)
- `CRLF` (Window)
- `LF` (UNIX)
- `CR` (Classic Mac)

Especially if you have some developers working on Windows they sometimes commit CRLF line endings accidentally.

**Comment by zpbx** [comment]
:+1: 

And this feature could support `end_of_line` option in EditorConfig.

**Comment by zpbx** [comment]
BTW, we might as well use `false` (instead of `'IGNORE'`) as the default value to switch off this check.

**Comment by crabbkw** [comment]
Pull request up that takes a stab at providing this support.

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
Fixed in #34 - this can be closed now

**Comment by schorfES** [comment]
Thank you, you're right!
