### ISSUE TITLE
Integration rc and allows you to declare settings in .lintspacesrc

### ISSUE THREAD

**Issue by evilebottnawi** [schorfES/node-lintspaces#28]
https://github.com/dominictarr/rc

**Comment by schorfES** [comment]
Is there a special need for this kind of configuration? Why not use the .editorconfig?

PR is welcome! ;-)

**Comment by evilebottnawi** [comment]
@schorfES not all options can settable in .editorconfig. Also all popular utilities for lintint support .*rc config file

**Comment by schorfES** [comment]
Ah okay... You're right. An integration into lintint would also be nice!

I'll try to create an implementation as soon as possible. The settings load process would look like this if both files are configured:

1. load ```.lintspacesrc```
2. load ```.editorconfig```

The reason for this is that the editorconfig can contain different settings depending on filetypes and I think this file is more relevant. In a second step we can think about the filetype settings into the rc as well... What do you think?

**Comment by evilebottnawi** [comment]
@schorfES i think it is correctly

**Comment by schorfES** [comment]
I've added a feature branch ["feature/rc-integration "](https://github.com/schorfES/node-lintspaces/tree/feature/rc-integration) for this. @evilebottnawi please try if the new option ```rcconfig``` fits for your purposes.

You may also take a look into the changes 6257a5a7ceea5ab016a1141c6b5b5362b0247a34 and 368812d2c13908c67909982e3ef18d43bde05d0f ([Documentation](https://github.com/schorfES/node-lintspaces/blob/feature/rc-integration/docs/options.md#rcconfig-option))

**Comment by evilebottnawi** [comment]
@schorfES sounds good, all perfectly, thanks

**Comment by josiahsprague** [comment]
Are there any docs on what `.lintspacesrc` is, and how to use it? It sounds like something that might be useful to me. I'm having trouble getting the `.editorconfig` file working with node-lintspaces anyway.

**Comment by schorfES** [comment]
Add a small example configuration into the [documentation](https://github.com/schorfES/node-lintspaces/blob/feature/rc-integration/docs/options.md#rcconfig-option). I will release this feature in the upcoming week.

**Comment by schorfES** [comment]
Published a new version 0.4.0 of lintspaces and also a new version of grunt-lintspaces at 0.7.2 at npm. 

@AlbertoElias please update gulp-lintspaces.
@evanshortiss please update the cli including a new flag for the .rcconfig ```.lintspacesrc```

Thanks in advance to @AlbertoElias and @evanshortiss!!!
