### ISSUE TITLE
UTF-8 charset

### ISSUE THREAD

**Issue by 807811b0-1373-11e5-b60b-1697f925ec7b** [schorfES/node-lintspaces#35]
EditorConfig has an option for `charset = utf-8` but it is not possible to validate this using this package. It would be a useful check. The only valid option for charset would be `utf-8`.

**Comment by schorfES** [comment]
Detecting a charset of a file is quite difficult. Files generally indicate their encoding with a file header. However, even reading the header you can never be sure what encoding a file is really using. Maybe there is an npm module out there which can handle the detection of the encoding and lintspaces can use it as dependency, but I didn't see that detection functionality in this project. I'll be fine with a PR to add the charset option.

**Comment by schorfES** [comment]
I'll close this for now.
