### ISSUE TITLE
IndentationGuess Rule #2 - indentation is less than previous line.

### ISSUE THREAD

**Issue by dpagini** [schorfES/node-lintspaces#37]
The rules of indentationGuess are as follows:

> // The indentation of the current line is correct when:
// * the amount of indentations is equal to the previous or
// * the amount of indentations is less than the previous line or
// * the amount of indentations is one more than the previous line
// * the amount of indentations is zero and the lines length is also
//   zero which is an empty line without trailing whitespaces

According to these rules, the following code PASSES:
```js
var fake = function() {
  var n = 0, x = 0;
  for (n = 0; n < 10; n++) {
    for (x = 0; x < 10; x++) {
 console.log('improper indentation');
    }
  }
}
```

This passes rule 2, above. Rule 2 _should read_:

> // * the amount of indentations is **one** less than the previous line or

**Comment by dpagini** [comment]
Hmm... not sure how I can do this...
```js
	switch(foo) {
		case 'hello':
				window.alert('hello');
			break;
		case 'hi':
			window.alert('hi');
			break;
	}
```

Can't figure out how to validate that last line.

**Comment by schorfES** [comment]
I think this should fail. I've change the comment in commit 8320593. Okay so far?

**Comment by dpagini** [comment]
Yep, the rule change is helpful, it just seems to me that we aren't testing for that updated rule. I was trying to work on a PR for that, but I'm having trouble with the last bit of code I pasted. The switch case starts at 1 indentation, let's say. The "case" statement is 2 indents in, the logic is 3 indents in, but the closing brace is back to 1. So here, we go from 3 indents to 1 indent on the last line, which sort of breaks the rule we're talking about here. I'm not sure how this should be handled...
Does that make sense?

**Comment by schorfES** [comment]
Sorry for the long delay!

I think that's the reason for the _is less_ in the previous version instead of _is one less_ in the new one from https://github.com/schorfES/node-lintspaces/commit/8320593d110a26f79fa813154e79b78b1694f11c which should be already handled by this line: [Validator.js:582](https://github.com/schorfES/node-lintspaces/blob/8320593d110a26f79fa813154e79b78b1694f11c/lib/Validator.js#L582)

In you example `indentation - indentationPrevious <= 1`will be `1 - 3 <= 1` --> true --> a valid indentation

What do you think? undo the change of the comment?

**Comment by dpagini** [comment]
Yeah, I mean your reasoning the logic is the way it is makes sense as a workaround, but it does provide a flawed workaround (see my first comment). The reason I had created this issue is b/c I saw some devs submitting the code in my initial comment. It's probably much bigger than a breadbox ask though, or at least one I'm not invested in fixing. Sorry...  =/

**Comment by schorfES** [comment]
Yes, but in that case above you will need to parse the language, to see if there is an error. This is the reason why the option is named _guess indentation_. Lintspaces should be language independent. You can add some parsing for brackets which will work for _javascript_, but this will also fail in you switch/case construct and in languages like _html_, _python_ etc.

But I need to undo the commit 8320593d110a26f79fa813154e79b78b1694f11c – am I right?

**Comment by dpagini** [comment]
> This is the reason why the option is named guess indentation.

Good point. 😆 👍 

Yes, I think that commit does not make much sense after this discussion. The "old" language seems more correct.

**Comment by schorfES** [comment]
😆

Okay, I will undo the commit... \o/
