### ISSUE TITLE
What is the benefit of this tool?

### ISSUE THREAD

**Issue by jitendravyas** [schorfES/node-lintspaces#38]

**Comment by schorfES** [comment]
This tool is a validator for different kinds of whitespaces in sourcefiles. I hope you find all additional informations in the [README](https://github.com/schorfES/node-lintspaces/blob/master/README.md) file – if not, please ask ;-)

**Comment by jitendravyas** [comment]
I use a tool called stylelint which also has some rules for space so i was wondering if this tool can do more and i guess in any file.

**Comment by schorfES** [comment]
Hopefully! Its meant to be not a language or sytax specific linter. Feel free to try...

**Comment by jitendravyas** [comment]
I came across this tool https://github.com/prettier/prettier I'm not sure what benefit it has over lintspace expect autofixing. I don't know if lintspaces can autofix code too
