### ISSUE TITLE
Can't validate files on Windows with .editorconfig

### ISSUE THREAD

**Issue by SamVerschueren** [schorfES/node-lintspaces#40]
Could find some issues regarding Windows but the all seem resolved. This library works perfectly on Unix, but on Windows the call to `validator.getInvalidFiles()` just returns an empty object. Any ideas?

**Comment by SamVerschueren** [comment]
I already found out that it has something to do with `.editorconfig`. I pass down the rules through the `.editorconfig` while. If I log the `config` at [this line](https://github.com/schorfES/node-lintspaces/blob/master/lib/Validator.js#L206), it's always an empty object. This is the editorconfig that I use.

```
root = true

[*]
indent_style = tab
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{package.json,*.yml}]
indent_style = space
indent_size = 2
```

**Comment by SamVerschueren** [comment]
I changed [this block of code](https://github.com/schorfES/node-lintspaces/blob/master/lib/Validator.js#L201-L205) to the following

```js
// Load config for current path
config = editorconfig.parseSync(
	this._path, {
		config: path.basename(this._settings.editorconfig),
		root: path.dirname(this._settings.editorconfig)
	}
);
```

I have no clue if this is okay to do but at least it seems to work on Windows.

@jedmao Any ideas here? Couldn't find issues in the `editorconfig` repo regarding Windows.

**Comment by jedmao** [comment]
Sorry. No ideas.

**Comment by schorfES** [comment]
Hey, I currently can't test on a windows machine and the travis ci support for windows is only work in progress... If the configuration block for editorconfig works fine for you on windows, feel free to open a PR.

Please run the tests on your local windows machine. I'll also add the platforms for _linux_ and _osx_ into travis ci.

**Comment by SamVerschueren** [comment]
@schorfES You can use [AppVeyor](https://www.appveyor.com/) to test on Windows which is also free for opensource projects. Here is an example of an [`appveyor.yml`](https://github.com/SamVerschueren/listr/blob/master/appveyor.yml) file.

I want to do a PR to change the block of code, the only downside is that `editorconfig` won't search from the current path all the way up to the root of the filesystem because we change the root to the working directory. So it looks like a suboptimal solution. I haven't ran the tests of `editorconfig-core-js` on Windows, but to me it looks like the bug is somewhere in there. Not sure though.

**Comment by schorfES** [comment]
@SamVerschueren for what is the `root` property meant to be? It's not quite clear from the docs of _editorconfig-core-js_. I think the .editorconfig always has to be placed in the project root, which will be the `root` folder to be used for a validation task. So in this case the `root` property will be okay.

Why you want to go all the way up to the filesystem root like c:\` or `/` ?

**Comment by SamVerschueren** [comment]
That's how EditorConfig works. It goes all the way up in your filepath as long as you don't specify `root = true` in your `.editorconfig` file. If it finds a `.editorconfig` while where `root` is set to `true`, it will stop. So probably by adjusting that block of code to this

```js
// Load config for current path
config = editorconfig.parseSync(
	this._path, {
		config: path.basename(this._settings.editorconfig),
		root: path.dirname(this._settings.editorconfig)
	}
);
```

will break the traversal of editorconfig files. Whenever I'm back on my windows machine, I will try to set up a minimal case to reproduce this as I'm not sure if this bug is something in `lint-spaces` or in `editorconfig-core-js`.

**Comment by schorfES** [comment]
Ah, okay! First of all, thank you for the effort!!!

**Comment by schorfES** [comment]
Hi @SamVerschueren, this issue is quite old but I've managed to find and fix the issue.
