### ISSUE TITLE
setting dont allow bom

### ISSUE THREAD

**Issue by gemal** [schorfES/node-lintspaces#44]
would be nice with a setting that would NOT allow BOM in the start of the file

I have a BOM file that just passed though 

I ran:
`lintspaces --endOfLine 'lf' --newline --trailingspaces --indentation 'tabs' --verbose 

[testbom.txt](https://github.com/schorfES/node-lintspaces/files/1965049/testbom.txt)
testbom.txt`

**Comment by schorfES** [comment]
Hi @gemal, what CLI did you use and did you set the [allowsBOM](https://github.com/schorfES/node-lintspaces#allowsbom-option) option to `false` through that CLI?

**Comment by gemal** [comment]
I tried both with allowBOM or not
using version 0.4.0

should be very easy to reproduce. can you add the testbom.txt file to the tests and they should fail.

How can I help?

**Comment by schorfES** [comment]
Hi @gemal,

sorry for not responding such a long time. I've created a test setup to check if lintspaces detects your example file correctly. For me this works for spacings and tabs as expected. Can you try that setup for your self too?

[testbom.zip](https://github.com/schorfES/node-lintspaces/files/2195846/testbom.zip)

If this also works for you, we may need to dive a bit deeper into the CLI which I didn't test yet.

**Comment by schorfES** [comment]
Hey @gemal, could you already test the setup from the comment above?

**Comment by schorfES** [comment]
Closing this for now.
