### ISSUE TITLE
Single-line files are not caught by `newline` check.

### ISSUE THREAD

**Issue by the-t-in-rtf** [schorfES/node-lintspaces#70]
On [this line](https://github.com/schorfES/node-lintspaces/blob/main/lib/Validator.js#L429), the newline check is only run if the line number is greater than one.  This means that  files with a single line of content that lack a trailing newline are not reported as errors.

**Comment by schorfES** [comment]
Hello @the-t-in-rtf, thank you for the report and pointing to the effected line – sounds reasonable. I am going to test and fix this soonish.

**Comment by schorfES** [comment]
Hey @the-t-in-rtf,

i've added a [test case](https://github.com/schorfES/node-lintspaces/pull/72/commits/5f99afee7c1736695aa89d013854d3386d502374) and a [fix](https://github.com/schorfES/node-lintspaces/pull/72/commits/f12fa1c9c4912d185cbea01043ad16f2131a2ee4) into this PR: #72 

I think that fixes your issue, correct?
